sonar.projectKey=joa851_playerhub-backend-mean
sonar.organization=joa851
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/coverage/**,**/node_modules/**,**/Dockerfile
sonar.test.inclusions=tests/**/*.test.js
